//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPiB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class brand_info
    {
        public int brand_id { get; set; }
        public string brand_name { get; set; }
        public string telephone { get; set; }
        public string brand_web { get; set; }
        public string brand_logo { get; set; }
        public string brand_desc { get; set; }
        public int brand_status { get; set; }
        public int brand_order { get; set; }
        public string modified_time { get; set; }
    }
}
