//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPiB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_login
    {
        public int Id { get; set; }
        public string login_name { get; set; }
        public string password { get; set; }
        public string user_stats { get; set; }
        public string modified_time { get; set; }
        public string customer_id { get; set; }
    }
}
