//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPiB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int order_detail_id { get; set; }
        public int order_id { get; set; }
        public int product_id { get; set; }
        public string product_name { get; set; }
        public int product_cnt { get; set; }
        public decimal product_price { get; set; }
        public decimal average_cost { get; set; }
        public double weight { get; set; }
        public int w_id { get; set; }
        public string modified_time { get; set; }
    }
}
