//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPiB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_master
    {
        public int order_id { get; set; }
        public int order_sn { get; set; }
        public string customer_id { get; set; }
        public string shipping_user { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string district { get; set; }
        public string address { get; set; }
        public string payment_method { get; set; }
        public decimal order_money { get; set; }
        public decimal district_money { get; set; }
        public decimal shipping_money { get; set; }
        public decimal payment_money { get; set; }
        public string shipping_comp_name { get; set; }
        public string shipping_sn { get; set; }
        public string create_time { get; set; }
        public string shipping_time { get; set; }
        public string pay_time { get; set; }
        public string receive_time { get; set; }
        public string order_status { get; set; }
        public int order_point { get; set; }
        public string invoice_time { get; set; }
        public string modified_time { get; set; }
    }
}
