//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPiB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_info
    {
        public int product_id { get; set; }
        public string product_core { get; set; }
        public string product_name { get; set; }
        public string bar_code { get; set; }
        public int brand_id { get; set; }
        public int one_category_id { get; set; }
        public int two_category_id { get; set; }
        public int three_category_id { get; set; }
        public int supplier_id { get; set; }
        public decimal price { get; set; }
        public decimal average_cost { get; set; }
        public int publish_status { get; set; }
        public int audit_status { get; set; }
        public Nullable<double> weight { get; set; }
        public Nullable<double> length { get; set; }
        public Nullable<double> height { get; set; }
        public Nullable<double> width { get; set; }
        public string color_type { get; set; }
        public string production_date { get; set; }
        public string shelf_life { get; set; }
        public string descript { get; set; }
        public string indate { get; set; }
        public string modified_time { get; set; }
    }
}
