//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPiB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class supplier_info
    {
        public int supplier_id { get; set; }
        public string supplier_code { get; set; }
        public string supplier_name { get; set; }
        public string supplier_type { get; set; }
        public string link_man { get; set; }
        public string phone_number { get; set; }
        public string bank_name { get; set; }
        public string bank_account { get; set; }
        public string address { get; set; }
        public int supplier_status { get; set; }
        public string modified_time { get; set; }
    }
}
