//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPiB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse_product
    {
        public int wp_id { get; set; }
        public int product_id { get; set; }
        public int w_id { get; set; }
        public int current_cnt { get; set; }
        public int lock_cnt { get; set; }
        public Nullable<int> in_transit_cnt { get; set; }
        public Nullable<decimal> average_cost { get; set; }
        public string modified_time { get; set; }
    }
}
