//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPiB.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class warehouse_info
    {
        public int w_id { get; set; }
        public string warehouse_sn { get; set; }
        public string warehoust_name { get; set; }
        public string warehouse_phone { get; set; }
        public string contact { get; set; }
        public string province { get; set; }
        public string city { get; set; }
        public string distrct { get; set; }
        public string address { get; set; }
        public int warehouse_status { get; set; }
        public string modified_time { get; set; }
    }
}
